smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: '<username>'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true

public_host: 'public.domain.com'

inv_db_ip: '192.168.0.15'

owner:
  title: 'Company'
  subtitle: 'Company Subtitle'
  address: 'Some street 123 - City'
